# Generated by Django 5.1 on 2024-09-13 23:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(max_length=50)),
                ('client_password', models.CharField(max_length=50)),
                ('client_avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('client_email', models.CharField(max_length=50)),
                ('client_tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_username', models.CharField(max_length=50)),
                ('contact_avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_tel', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('contact_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_with', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('message_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='client.client')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='client.client')),
            ],
        ),
    ]
